version: '3'

services:
  db:
    image: mariadb:latest
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
    env_file:
      - db_secret.env

  redis:
    image: redis:alpine
    command: --requirepass somepwd # SET THIS
    restart: always
    environment:
      - REDIS_HOST_PASSWORD=somepwd # SET THIS

  app:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      - REDIS_HOST_PASSWORD=somepwd # SET THIS
      - NEXTCLOUD_TRUSTED_DOMAINS=
      - PHP_MEMORY_LIMIT=102400M # 100 GB
      - PHP_UPLOAD_LIMIT=102400M # 100 GB
    env_file:
      - db_secret.env
    depends_on:
      - db
      - redis

  cron:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

volumes:
  db:
  nextcloud:
